version: 1.3.1
slug: ps5_mqtt
name: PS5 MQTT
description: Control Sony PlayStation 5 devices via MQTT
url: https://github.com/FunkeyFlo/ps5-mqtt/tree/main/add-ons/ps5-mqtt
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
services:
  - mqtt:need
boot: auto
host_network: true
ingress: true
ingress_port: 0
panel_icon: mdi:sony-playstation
ports:
  8645/tcp: null
ports_description:
  8645/tcp: PS5 MQTT Web Interface
map:
  - config:rw
options:
  mqtt: {}
  logger: '@ha:ps5:*'
  device_check_interval: 5000
  device_discovery_interval: 60000
  account_check_interval: 5000
  include_ps4_devices: false
  psn_accounts: []
schema:
  mqtt:
    host: str?
    port: port?
    user: str?
    pass: str?
  psn_accounts:
    - username: str?
      npsso: str
      preferred_ps5: str?
      preferred_ps4: str?
  logger: str?
  device_discovery_broadcast_address: str?
  device_check_interval: int
  device_discovery_interval: int
  account_check_interval: int
  include_ps4_devices: bool
stdin: true
image: ghcr.io/funkeyflo/ps5-mqtt/{arch}
